version: '3'
services:
  acapy-with-plugin:
    image: acapy-with-plugin
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 3001:3001
    command: start -it http 0.0.0.0 3000 -ot http -e http://acapy-with-plugin:3000 --no-ledger --admin 0.0.0.0 3001 --admin-insecure-mode --plugin my_plugin

  #*************************************************************
  # tester: drives tests in a                                  *
  # "Juggernaut" fashion!                                      *
  #*************************************************************

  tests:
      container_name: juggernaut
      build:
        context: .
        dockerfile: Dockerfile.test.runner
      environment:
        - WAIT_BEFORE_HOSTS=6
        - WAIT_HOSTS=acapy-with-plugin:3001
        - WAIT_HOSTS_TIMEOUT=60
        - WAIT_SLEEP_INTERVAL=1
        - WAIT_HOST_CONNECT_TIMEOUT=30
        - AGENT_HOST=acapy-with-plugin
        - AGENT_PORT=3000
        - AGENT_BACKCHANNEL_PORT=3001
      depends_on:
        - acapy-with-plugin
