version: '3'
services:
  acapy-with-plugin:
    image: acapy-with-plugin
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./int/healthcheck.py:/usr/src/app/healthcheck.py:z,ro
    command: >
      start
      -it http 0.0.0.0 3000
      -ot http
      -e http://acapy-with-plugin:3000
      --no-ledger
      --admin 0.0.0.0 3001
      --admin-insecure-mode
      --plugin my_plugin
    healthcheck:
      test: ["CMD-SHELL", "python", "healthcheck.py", "http://localhost:3001/status/live"]
      start_period: 10s
      interval: 3s
      timeout: 5s
      retries: 5


  #*************************************************************
  # tester: drives tests in a                                  *
  # "Juggernaut" fashion!                                      *
  #*************************************************************

  tests:
      container_name: juggernaut
      build:
        context: .
        dockerfile: Dockerfile.test.runner
      environment:
        - AGENT_HOST=acapy-with-plugin
        - AGENT_PORT=3000
        - AGENT_BACKCHANNEL_PORT=3001
      depends_on:
        acapy-with-plugin:
          condition: service_healthy
