FROM python:3.9-slim-bullseye
WORKDIR /usr/src/app/

# Install and Configure Poetry
RUN apt-get update && apt-get install -y curl
ENV POETRY_VERSION=1.4.2
ENV POETRY_HOME=/opt/poetry
RUN curl -sSL https://install.python-poetry.org | python -
ENV PATH="/opt/poetry/bin:$PATH"
RUN poetry config virtualenvs.in-project true

COPY pyproject.toml poetry.lock ./
RUN poetry install

COPY tests/* tests/

ENTRYPOINT ["poetry", "run", "pytest"]
