# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Code Quality Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  POETRY_VERSION: 1.4.2
  BLACK_VERSION: 22.8.0

jobs:
  format:
    name: Formatting (with black)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
            python-version: 3.9
      - name: Cache python environment
        id: cache-env
        uses: actions/cache@v2
        with:
            path: ${{ env.pythonLocation }}
            key: ${{ runner.os }}-formatting-black-${{ env.BLACK_VERSION }}
      - name: Install black
        if: steps.cache-env.outputs.cache-hit != 'true'
        run: |
            pip install black==${{ env.BLACK_VERSION }}
      - name: Black Format Check
        run: |
            black --check .

  test:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
        
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install dependencies
        run: poetry install
      - name: Run unit tests with pytest
        run: |
          poetry run pytest ./tests
          
  int:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run integration tests
      run: |
        docker-compose -f int/docker-compose.yml run tests
    - name: Print logs on failure
      if: failure()
      run: |
        docker-compose -f int/docker-compose.yml logs acapy-with-plugin
    - name: Clean up integration tests
      if: always()
      run: |
        docker-compose -f int/docker-compose.yml down
